print(",--------------------------------.")
print("| o21ooooooooooooooooo J8     +====")
print("| ooooo4oooooooooooooo      P | USB")
print("|  Wi                     ooo +====")
print("|  Fi  Pi Model 3B+ V1.3  ooE    |")
print("|        ,----.               +====")
print("| |D|    |SoC |               | USB")
print("| |S|    |    |               +====")
print("| |I|    `----'                  |")
print("|                   |C|     +======")
print("|                   |S|     |   Net")
print("| pwr        |HDMI| |I||A|  +======")
print("`-| |--------|    |----|V|-------'")
print("")
print("     +--------------------------------------+")
print("     |                +---------------++---+|")
print("     | +-------+      |               ||   ||")
print("     | |       |      |               ||   ||")
print("     | |   1   |GND   |               ||   ||")
print("     | |   2   |VCC   |               |+---+|")
print("     | |   3   |      |               |+---+|")
print("     | |   4   |SIG   |               ||   ||")
print("     | |       |      |               ||   ||")
print("     | +-------+      |               ||   ||")
print("     |                +---------------++---+|")
print("     +--------------------------------------+")
